---
# tasks file for ansible-role-sshd
- name: Configure sshd
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "Port", value: "{{ hostvars['gol_server'].ansible_sshport }}" }
    - { key: "PubkeyAuthentication", value: "yes" }
  notify: restart sshd
